version: '3'
services:
    php-fpm:
        build:
            context: .
            dockerfile: ./doc/php-fpm/Dockerfile
            args:
                UID: ${USER_ID}
                GID: ${GROUP_ID}
        image: ${APP_NAME}-php-fpm
        container_name: php-fpm
        working_dir: /var/www
        depends_on:
            - mysql
            - nginx
        volumes:
            - ./src:/var/www
            - ./doc/php-fpm/php.ini-development:/usr/local/etc/php/php.ini
        restart: on-failure

    nginx:
        build:
            context: .
            dockerfile: ./doc/nginx/Dockerfile
        image: ${APP_NAME}-nginx
        container_name: nginx
        environment:
            APP_DOMAIN: ${APP_DOMAIN}
        volumes:
            - ./src/public:/var/www/public
            - ./doc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./doc/nginx/templates:/etc/nginx/templates
            - ./doc/nginx/config:/etc/nginx/config
        ports:
            - ${NGINX_PORT}:80
        restart: on-failure

    mysql:
        image: mysql:latest
        container_name: mysql
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./doc/mysql:/docker-entrypoint-initdb.d
            - mysql-data:/var/lib/mysql
        restart: on-failure

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        depends_on:
            - mysql
        ports:
            - ${PHPMYADMIN_PORT}:80
        environment:
            PMA_HOST: mysql
        logging:
            driver: none
        restart: on-failure

volumes:
    mysql-data:
