version: '3'
services:
    php-fpm:
        build:
            context: .
            dockerfile: ./doc/php-fpm/Dockerfile
        image: ${APP_NAME}-php-fpm
        container_name: php-fpm
        working_dir: /var/www
        restart: always

    nginx:
        build:
            context: .
            dockerfile: ./doc/nginx/Dockerfile
        image: ${APP_NAME}-nginx
        container_name: nginx
        environment:
            APP_DOMAIN: ${APP_DOMAIN}
        ports:
            - ${NGINX_PORT}:80
        restart: always
